" set the runtime path to include Vundle and initialize
let mapleader = ","

" git clone https://github.com/VundleVim/Vundle.vim.git  ~/.vim/bundle/Vundle.vim
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-eunuch'
Plugin 'sheerun/vim-polyglot'
"my Bundle here:
" original repos on github
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'jiangmiao/auto-pairs'
Plugin 'altercation/vim-colors-solarized'
Plugin 't9md/vim-quickhl'
Plugin 'mileszs/ack.vim'
Plugin 'bling/vim-airline'
Plugin 'elzr/vim-json'
"..................................
" vim-scripts repos
Plugin 'godlygeek/tabular'
Plugin 'jzdxeb/vim-snippets'
call vundle#end()            " required

filetype on
filetype plugin on
filetype plugin indent on

" solarised
syntax enable
syntax on
set background=dark
colorscheme solarized

" ctrlp
let g:ctrlp_map = '<C-p>'
let g:ctrlp_cmd = 'CtrlP'

"for airline'
if !exists('g:airline_symbols')
	let g:airline_symbols = {}
endif
let g:airline_left_sep = '▶'
let g:airline_left_alt_sep = '❯'
let g:airline_right_sep = '◀'
let g:airline_right_alt_sep = '❮'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'

" *.cpp 和 *.h 间切换
nmap <silent> <Leader>sw :FSHere<cr>

" for nerd tree
nmap <F2> :NERDTreeToggle<CR>
let NERDTreeWinPos="right"

"再次打开光标位置在上次退出时的位置
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif  

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") &&b:NERDTreeType == "primary") | q | endif
autocmd Filetype gitcommit setlocal spell textwidth=72
autocmd BufWritePost $MYVIMRC source $MYVIMRC
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4
set noswapfile
" 关闭兼容模式
set nocompatible
" vim 自身命令行模式智能补全
set wildmenu

" 搜索时大小写不敏感
" set ignorecase


" 开启实时搜索功能
set incsearch

" 总是显示状态栏
set laststatus=2
set ruler
set statusline="%t%m"

" 打开行号 和相对行号
set nu
set relativenumber

set backspace=2
set foldlevelstart=99
set hlsearch
" indent 4 space 
set shiftwidth=4
" tab = 4 space
set softtabstop=4

" tab 4 space
set tabstop=4

set encoding=utf-8 nobomb
set fileencodings=ucs-bom,utf-8,cp936
set binary
set noeol
set modeline
set modelines=4

" disable error bells
set noerrorbells
" set showmode
set title
set pastetoggle=<F9>
set showcmd
set showmatch
set formatoptions-=r
"set shell=bash\ -i
" 打开光标行死高亮
" set cursorcolumn "CursorColumn
set cursorline
set cursorcolumn

nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K> 
nnoremap <C-L> <C-W><C-L> 
nnoremap <C-H> <C-W><C-H> 
nnoremap <F3> :Ack! 

imap jk  <esc><esc>
imap kj  <esc><esc>

nmap <leader>w :w<CR>
nmap <leader>wq :wq<CR>
nmap <leader>q :q!<CR>

if executable('ag')
	let g:ackprg = 'ag --vimgrep'
endif