# ~/.zshrc
# Path to your oh-my-zsh installation.
#source ~/.dotfiles/config/rc

export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME='~/.virtualenvs'
export PATH="$WORKON_HOME/bin:$PATH"

ZSH_THEME="dstufft"
HIST_STAMPS="mm/dd/yyyy"
HISTSIZE=10000
SAVEHIST=10000
SHARE_HISTORY=0

plugins=(iterm2 tig brew zsh_reload  git autojump themes)

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -n -R  . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Aliases
alias cppcompile='c++ -std=c++11 -stdlib=libc++'
setopt nonomatch


source $ZSH/oh-my-zsh.sh
# export LSCOLORS='CxfxcxdxbxegedabagGxGx'
# export CLICOLOR='Yes'

compdef sshrc=ssh
bindkey \^U backward-kill-line

export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH
