# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster/agnoster"
#ZSH_THEME="robbyrussell"

HIST_STAMPS="mm/dd/yyyy"


plugins=(osx brew brew-cask sudo zsh_reload my git autojump docker cp)

# User configuration

export PATH=.:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
export MANPATH="/usr/local/share/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# Example aliases
alias czsh="vi ~/.zshrc"
alias cvi="vi ~/.vimrc"
alias cls="clear"
alias ll="ls -rtlh"
alias vi="vim"

#macdown 打开md
alias -s md=vi
alias -s c=vi
alias -s cpp=vi
alias -s h=vi

# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -n -R  . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }

# Aliases
alias cppcompile='c++ -std=c++11 -stdlib=libc++'

