# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  #source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

[ -f ~/.dotfiles/config/rc ] && source ~/.dotfiles/config/rc

if test -n "$ZSH_VERSION"; then
	PROFILE_SHELL=zsh
	setopt histignorespace           # skip cmds w/ leading space from history
	alias czsh="vim ~/.zshrc"
fi

HIST_STAMPS="mm/dd/yyyy"
HISTSIZE=10000
SAVEHIST=10000
SHARE_HISTORY=0

if command -v git > /dev/null 2>&1; then 
	syncrepo(){
	  for D in `find . -type d -depth 1`
	  do
	    pushd $D
		git submodule deinit -f .
		git stash 
	    git pull --rebase
	    git submodule update --init -f  -r
		git stash  pop
	    popd
	  done
	}
fi
function ii() {
	echo -e "\nYou are logged on ${RED}$HOST"
	echo -e "\nAdditionnal information:$NC " ; uname -a
	echo -e "\n${RED}Users logged on:$NC " ; w -h
	echo -e "\n${RED}Current date :$NC " ; date
	echo -e "\n${RED}Machine stats :$NC " ; uptime
	echo -e "\n${RED}Current network location :$NC " ; scselect
	echo -e "\n${RED}Public facing IP Address :$NC " ;myip
	#echo -e "\n${RED}DNS Configuration:$NC " ; scutil --dns
	echo
}


# FileSearch
function f() { find . -iname "*$1*" ${@:2} }
function r() { grep "$1" ${@:2} -n -R  . }

#mkdir and cd
function mkcd() { mkdir -p "$@" && cd "$_"; }
function src() { source ~/.zshrc }

# Aliases
alias cppcompile='c++ -std=c++11 -stdlib=libc++'
setopt nonomatch

[[ ! -d ~/.zplug ]] \
	&& git clone https://github.com/zplug/zplug ~/.zplug \
	&& echo "zplug clone"
[[ ! -f ~/.zplug/init.zsh ]] || source ~/.zplug/init.zsh

export ZPLUG_HOME=~/.zplug


# Make sure to use double quotes
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"

# Supports oh-my-zsh plugins and the like
zplug "plugins/git",   from:oh-my-zsh
zplug "plugins/brew",   from:oh-my-zsh
zplug "plugins/reload",   from:oh-my-zsh
zplug "plugins/autojump", from:oh-my-zsh
zplug "plugins/kubectl",   from:oh-my-zsh
zplug "plugins/kube-ps1",   from:oh-my-zsh
zplug "themes/ys",   from:oh-my-zsh
zplug "plugins/cp",   from:oh-my-zsh

#zplug "romkatv/powerlevel10k", as:theme, depth:1
zplug "k4rthik/git-cal", as:command, frozen:1

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
	zplug load --verbose
fi
zplug load 

# Then, source plugins and add commands to $PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
ZSH_THEME="ys"
export WORKON_HOME='~/.virtualenvs'
export PATH="$WORKON_HOME/bin:$PATH"
export GPG_TTY=$TTY
# export LSCOLORS='CxfxcxdxbxegedabagGxGx'
# export CLICOLOR='Yes'
export DYLD_LIBRARY_PATH=/usr/local/opt/openssl/lib:$DYLD_LIBRARY_PATH
export FPATH=${HOME}/.fpath:$FPATH
PROMPT='$(kube_ps1)'$PROMPT
